name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *'


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        spec-file: ["1_RegistrationTestRunner.spec.js", "BlogTestRunner.spec.js" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Test - ${{ matrix.spec-file }}
        run: npx playwright test tests/${{ matrix.spec-file }} --reporter=html

      - name: Upload HTML Report - ${{ matrix.spec-file }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.spec-file }}
          path: playwright-report/
